name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:

  publish:
    name: Amuze Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create Release
        run: gh release create ${{ github.ref_name }} --title "Amuze ${{ $(echo github.ref_name | rev | cut -d 'v' -f 1) }}" --notes "Initial release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
